name: Build, Test and Deploy Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências (exemplo com Node.js, altere conforme sua stack)
        run: |
          echo "Simulando etapa de build"
          # Exemplo: npm install, pip install -r requirements.txt, etc.
          echo "Build concluído"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: docker build -t flask-jwt-test .

      - name: Rodar testes
        run: docker run --rm flask-jwt-test python3 -m unittest test_app.py

      - name: Deploy na Vercel
        run: |
          echo "Chamando rota protegida com token JWT"
          curl -X GET https://teste-final-theta.vercel.app/protected \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0Nzg3MDQ5OCwianRpIjoiNGQ4ZWE4MTEtZjM0NC00M2MzLWFkYWUtMDNkZGRlZjk0Mzc3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzdWFyaW9fZXhlbXBsbyIsIm5iZiI6MTc0Nzg3MDQ5OCwiY3NyZiI6ImQxODcyODcyLWVhYzEtNDYzYi04Y2Q2LTI2M2ZkOWUwNjI1MiIsImV4cCI6MTc0Nzg3MTM5OH0.f2n8jlnaGhDiBSUca3cfr8Qoezag3TJwPzKeoOcy8JI"

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Fazer deploy no Vercel
        run: vercel --prod --token EKDKGIeJ0zQCB37oRJDLzas9 --yes
